opt_in_rules: # some rules are only opt-in
  - empty_count
  - redundant_nil_coalescing
  - switch_case_on_newline
  - force_unwrapping
  - conditional_returns_on_newline
  - closure_spacing
  - implicitly_unwrapped_optional
  - sorted_imports
  - valid_docs

included:
  - Sources

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Tests
  - Example

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - identifier_name

line_length: 130
