name: Bug Report
description: File a bug report.
labels: ["bug"]
assignees:
  - SvenTiigi
body:
  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: Please describe the bug.
      placeholder: Description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: What are the steps to reproduce?
      description: Please describe the steps to reproduce the bug.
      placeholder: |
        Step 1: ...
        Step 2: ...
        Step 3: ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior?
      description: Please describe the behavior you expect of WhatsNewKit.
      placeholder: I expect that WhatsNewKit would...
    validations:
      required: true
